#!/bin/bash

# Description: Check file exists in loops

# Process files. skip hidden ones
for file in * .*; do
    [[ "$file" == .* ]] && echo "Hidden file: $file" && continue
    [[ -f "$file" ]] || continue
    echo "Processing: $file"
done
