name: Deploy AWS Lambda

on:
    push:
        branches:
          - main
        paths:
          - 'ci-cd-pipelines/lambda-cicd/lambda/**'

jobs:
    deploy-lambda: # Name of job
        runs-on: ubuntu-latest # Sets or specifies runner
        environment: lambda-deploy # Specifies the environment name for the job (containing secrets)
        defaults:
          run:
            working-directory: ci-cd-pipelines/lambda-cicd/lambda/ # Sets the working directory for all run steps in this job
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python # Sets up python env
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install Dependencies # Installs any packages required for the lambda function
              run: |
                python -m pip install --upgrade pip
                pip install -r lambda/requirements.txt -t .

            - name: Configure AWS Credentials # Sets up AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Deploy Lambda Function # Zips lambda directory and updates lambda function
              run: |
                zip -r lambda.zip .
                aws lambda update-function-code --function-name test-cicd-lambda --zip-file fileb://lambda.zip